---
title: "ggplot_project"
author: "kaet"
date: "2022-12-08"
output: html_document
---

Context: This dataset is E.coli(microbe) DNA. The objective is to QC-check data exploration by ggplot

Data Source: https://raw.githubusercontent.com/Kaetkung/datarockieBatch6_project_1/main/ggplot_project/var_vcf.csv

library we use.
```{r}
library(tidyverse)
```

load data
```{r}
variants = read_csv("https://raw.githubusercontent.com/Kaetkung/datarockieBatch6_project_1/main/ggplot_project/var_vcf.csv")
glimpse(variants)
head(variants)
```

Check NA in data
```{r}
apply(variants, MARGIN = 2, function(col) sum(is.na(col)))
```


Data exploration
```{r}
#scatter plot between Depth and Position.
ggplot(variants, aes(POS, DP, color = sample_id)) + 
  geom_point(alpha = 0.6,size = 0.8) +
  labs(x = "Base Pair Position",
       y = "Read Depth (DP)") +
  ggtitle("Read Depth vs. Position") +
  theme_minimal()
```

```{r}
#scatter plot between Mapping quality and Position.
ggplot(variants, aes(POS, MQ, color = sample_id)) + 
  geom_point(alpha = 0.6,size = 0.8) +
  labs(x = "Base Pair Position",
       y = "Read Depth (DP)") +
  ggtitle("Read Depth vs. Position") +
  theme_minimal()
```

```{r}
#Faceting each sample_id scatter plot between Mapping quality and Position by vertically.
ggplot(variants, aes(POS, MQ, color = sample_id)) +
  geom_point(alpha = 0.6,size = 0.8) +
  labs(x = "Base Pair Position",
       y = "Mapping Quality (MQ)") +
  facet_grid(. ~ sample_id) +
  theme_bw() +
  theme(panel.grid = element_blank())
```

```{r}
#Faceting each sample_id scatter plot between Mapping quality and Position by horizontally.
ggplot(variants, aes(POS, MQ, color = sample_id)) +
  geom_point(alpha = 0.6,size = 0.8) +
  labs(x = "Base Pair Position",
       y = "Mapping Quality (MQ)") +
  facet_grid(sample_id ~ .) +
  theme_bw() +
  theme(panel.grid = element_blank())
```

```{r}
#Faceting each sample_id scatter plot between Quality and Position by horizontally.
ggplot(variants, aes(POS, QUAL, color = sample_id)) +
  geom_point(alpha = 0.6,size = 0.8) +
  labs(x = "Base Pair Position",
       y = "PHRED-sacled Quality (QUAL)") +
  facet_grid(sample_id ~ .) +
  theme_bw() +
  theme(panel.grid = element_blank())
```


```{r}
#Faceting each sample_id scatter plot between frequency of INDEL and not INDEL variant.
ggplot(data = variants, aes(x = INDEL, fill = sample_id)) +
  geom_bar() +
  facet_grid(sample_id ~ .)
```



